### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [ranjanZ/ICDAR_Binarization#1]
@ranjanZ Documentation for training and predicting

**Comment by ranjanZ** [comment]
Thank for your interest. We will soon upload  Readme.md with documentation.

**Comment by ranjanZ** [comment]
Updated!  Let me know if you face any further problem. Also feel free to send  pull requests. 
Thanks.

**Comment by ghost** [comment]
Thanks man, you're amazing
